import type { PresetId, Theme } from "@/lib/types";

const baseBackground = {
  solid: "#fafafa",
  gradientFrom: "#f5f3ff",
  gradientTo: "#e0e7ff",
  gradientAngle: 135,
  imageUrl: "",
  noiseColor: "#000000",
  noiseOpacity: 0.05,
};

export const PRESETS: Record<PresetId, { label: string; blurb: string; theme: Theme }> = {
  minimal: {
    label: "Minimal",
    blurb: "Quiet, airy, and typographic",
    theme: {
      preset: "minimal",
      mode: "light",
      background: { ...baseBackground, type: "solid", solid: "#fafaf9" },
      fontHeading: "inter",
      fontBody: "inter",
      primary: "#18181b",
      accent: "#6366f1",
      radius: 20,
      shadow: "soft",
      spacing: 14,
      borderWidth: 0,
      columns: 4,
    },
  },
  developer: {
    label: "Developer",
    blurb: "Monospace, terminal-inspired",
    theme: {
      preset: "developer",
      mode: "dark",
      background: { ...baseBackground, type: "solid", solid: "#0a0a0a" },
      fontHeading: "spaceGrotesk",
      fontBody: "jetbrainsMono",
      primary: "#e4e4e7",
      accent: "#22d3ee",
      radius: 10,
      shadow: "none",
      spacing: 10,
      borderWidth: 1,
      columns: 4,
    },
  },
  brutalist: {
    label: "Brutalist",
    blurb: "Bold borders, hard shadows, no fuss",
    theme: {
      preset: "brutalist",
      mode: "light",
      background: { ...baseBackground, type: "solid", solid: "#fdf6e3" },
      fontHeading: "spaceMono",
      fontBody: "spaceMono",
      primary: "#111111",
      accent: "#ff3d00",
      radius: 2,
      shadow: "hard",
      spacing: 16,
      borderWidth: 3,
      columns: 4,
    },
  },
  y2k: {
    label: "Y2K",
    blurb: "Chrome, gradients, and nostalgia",
    theme: {
      preset: "y2k",
      mode: "light",
      background: { ...baseBackground, type: "gradient", solid: "#ffe6fb", gradientFrom: "#c9f7ff", gradientTo: "#ffd6f5", gradientAngle: 120 },
      fontHeading: "pressStart2p",
      fontBody: "plusJakarta",
      primary: "#1a1a2e",
      accent: "#ff2ec4",
      radius: 24,
      shadow: "medium",
      spacing: 12,
      borderWidth: 2,
      columns: 4,
    },
  },
  editorial: {
    label: "Editorial",
    blurb: "Serif headlines, magazine feel",
    theme: {
      preset: "editorial",
      mode: "light",
      background: { ...baseBackground, type: "solid", solid: "#f7f4ef" },
      fontHeading: "fraunces",
      fontBody: "inter",
      primary: "#231f20",
      accent: "#a3402b",
      radius: 6,
      shadow: "none",
      spacing: 18,
      borderWidth: 1,
      columns: 4,
    },
  },
  glass: {
    label: "Glass",
    blurb: "Frosted, translucent, dreamy",
    theme: {
      preset: "glass",
      mode: "dark",
      background: { ...baseBackground, type: "gradient", gradientFrom: "#3a1c71", gradientTo: "#1e3c72", gradientAngle: 145 },
      fontHeading: "instrumentSerif",
      fontBody: "inter",
      primary: "#f5f5f7",
      accent: "#a78bfa",
      radius: 28,
      shadow: "soft",
      spacing: 14,
      borderWidth: 1,
      columns: 4,
    },
  },
  pixel: {
    label: "Pixel",
    blurb: "8-bit, blocky, playful",
    theme: {
      preset: "pixel",
      mode: "light",
      background: { ...baseBackground, type: "noise", solid: "#dff5ff", noiseColor: "#000000", noiseOpacity: 0.06 },
      fontHeading: "pressStart2p",
      fontBody: "jetbrainsMono",
      primary: "#101828",
      accent: "#22c55e",
      radius: 0,
      shadow: "hard",
      spacing: 12,
      borderWidth: 2,
      columns: 4,
    },
  },
};

export const DEFAULT_THEME: Theme = PRESETS.minimal.theme;
